// Vercel Serverless Function - serves leads JSON
export default function handler(request, response) {
    // In production, this would read from a database or static JSON
    // For demo, we'll return an empty array - leads are loaded via import
    response.status(200).json({ leads: [], total: 0 });
}

// Alternative: read from static file
import fs from 'fs';
import path from 'path';

export const config = {
    maxDuration: 10,
};

export default function handler(req, res) {
    try {
        // Try to read leads.json (will be generated by scraper)
        const leadsPath = path.join(process.cwd(), '..', 'leads.json');
        const summaryPath = path.join(process.cwd(), '..', 'summary.json');
        
        let leads = [];
        let summary = { total_leads: 0, cities: {}, categories: {} };
        
        if (fs.existsSync(leadsPath)) {
            leads = JSON.parse(fs.readFileSync(leadsPath, 'utf8'));
        }
        
        if (fs.existsSync(summaryPath)) {
            summary = JSON.parse(fs.readFileSync(summaryPath, 'utf8'));
        }
        
        res.setHeader('Access-Control-Allow-Origin', '*');
        res.status(200).json({ leads, summary });
    } catch (e) {
        res.status(200).json({ leads: [], summary: {} });
    }
}